services:
  app:
    build: .
    image: jhj0517/advancedliveportrait-webui:latest

    volumes:
      # Update paths to mount models and output paths to your custom paths like this, e.g:
      # - C:/AdvancedLivePortrait-WebUI/custom-model-path:/AdvancedLivePortrait-WebUI/models
      # - C:/AdvancedLivePortrait-WebUI/custom-output-path:/AdvancedLivePortrait-WebUI/outputs
      - /AdvancedLivePortrait-WebUI/models
      - /AdvancedLivePortrait-WebUI/outputs

    ports:
      - "7860:7860"

    stdin_open: true
    tty: true

    entrypoint: ["python", "app.py", "--server_port", "7860", "--server_name", "0.0.0.0",]

    # If you're not using nvidia GPU, Update device to match yours.
    # See more info at : https://docs.docker.com/compose/compose-file/deploy/#driver
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]